# Generated by Django 5.2.5 on 2026-06-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_url',
            field=models.ImageField(upload_to='projects/'),
        ),
    ]
