# Generated by Django 5.2.5 on 2026-06-12 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_project_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='long_description',
            field=models.TextField(blank=True, help_text='توضیحات کامل برای صفحه جزئیات', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='video_url',
            field=models.URLField(blank=True, help_text='لینک یوتیوب یا آپارات', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='توضیح کوتاه برای کارت پروژه'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_url',
            field=models.ImageField(help_text='عکس اصلی (Thumbnail)', upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, help_text='لینک دمو یا سایت'),
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='api.project')),
            ],
        ),
    ]
